import './globals.css';

import { SiteHeader } from '@/components/site-header';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen flex-col items-center bg-background">
          <ThemeProvider attribute="class" defaultTheme="light">
            <SiteHeader />
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
